// Don't edit this file, as it is generated by dredger
package server

import (
	"asyncService/entities"
	"encoding/json"
	"log"

	"github.com/gorilla/websocket"
	"github.com/nats-io/nats.go"
)

func Subscribetohumidityreadings(nc *nats.Conn, ws *websocket.Conn) *nats.Subscription {

	// Subscribe to "weather-humidity"
	Sub, err := nc.Subscribe("weather-humidity", func(msg *nats.Msg) {
		envweatherHumidity := entities.Envelope{
			Type: "weatherHumidity",
			Data: msg.Data,
		}
		outweatherHumidity, err := json.Marshal(envweatherHumidity)
		if err != nil {
			log.Println("Error marshaling weatherHumidity envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outweatherHumidity); writeErr != nil {
			log.Println("Error writing weatherHumidity to WebSocket:", writeErr)
		}

		envweatherHumidityAlert := entities.Envelope{
			Type: "weatherHumidityAlert",
			Data: msg.Data,
		}
		outweatherHumidityAlert, err := json.Marshal(envweatherHumidityAlert)
		if err != nil {
			log.Println("Error marshaling weatherHumidityAlert envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outweatherHumidityAlert); writeErr != nil {
			log.Println("Error writing weatherHumidityAlert to WebSocket:", writeErr)
		}

	})
	if err != nil {
		log.Println("NATS subscribe to weather-humidity failed:", err)
		return nil
	}

	return Sub
}

func Subscribetotemperaturereadings(nc *nats.Conn, ws *websocket.Conn) *nats.Subscription {

	// Subscribe to "weather-temperature"
	Sub, err := nc.Subscribe("weather-temperature", func(msg *nats.Msg) {
		envweatherTemperature := entities.Envelope{
			Type: "weatherTemperature",
			Data: msg.Data,
		}
		outweatherTemperature, err := json.Marshal(envweatherTemperature)
		if err != nil {
			log.Println("Error marshaling weatherTemperature envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outweatherTemperature); writeErr != nil {
			log.Println("Error writing weatherTemperature to WebSocket:", writeErr)
		}

		envweatherTemperatureAlert := entities.Envelope{
			Type: "weatherTemperatureAlert",
			Data: msg.Data,
		}
		outweatherTemperatureAlert, err := json.Marshal(envweatherTemperatureAlert)
		if err != nil {
			log.Println("Error marshaling weatherTemperatureAlert envelope:", err)
			return
		}
		if writeErr := ws.WriteMessage(websocket.TextMessage, outweatherTemperatureAlert); writeErr != nil {
			log.Println("Error writing weatherTemperatureAlert to WebSocket:", writeErr)
		}

	})
	if err != nil {
		log.Println("NATS subscribe to weather-temperature failed:", err)
		return nil
	}

	return Sub
}
