// Don't edit this file, as it is generated by dredger
// TODO: use wire for dependencies

package main

import (
	"multiService/core"
	"multiService/core/log"
	"multiService/core/tracing"
	"multiService/rest"
	"multiService/rest/middleware"
	"multiService/web"
	_ "embed"
	"context"

	"github.com/labstack/echo/v4"
	echoMiddleware "github.com/labstack/echo/v4/middleware"
	"github.com/labstack/echo-contrib/echoprometheus"
	// "go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho"
)

//go:embed web
var embeddedFS embed.FS

func main() {
	log.Setup(core.AppConfig.Name, core.Service, core.AppConfig.LogFile, core.AppConfig.LokiServer, core.AppConfig.LokiKey, core.AppConfig.LokiLabels, core.AppConfig.LokiBuffersize, core.AppConfig.LokiMaxDelay, core.AppConfig.Debug)

	// init Opentelemetry
    if core.AppConfig.Tracing {
    	tp, err := tracing.InitTracer()
    	if err != nil {
    		log.Fatal().Err(err).Msg("Initializing tracer failed")
    	}
    	defer func() {
    		if err := tp.Shutdown(context.Background()); err != nil {
    			log.Warn().Err(err).Msg("Error shutting down tracer provider")
    		}
    	}()
    }

    mainSvc()

    log.Info().Str("port", core.AppConfig.PortNb).Msg("Starting web service")

	// start echo server
	e := echo.New()
	e.Use(echoprometheus.NewMiddleware(core.AppConfig.Service)) // adds middleware to gather metrics

	e.Use(echoMiddleware.CORS())
	e.Use(middleware.LoggerHandler)
	// e.Use(otelecho.Middleware(core.AppConfig.Sid))
	e.Use(middleware.PolicyHandler) // Policy Enforcement Point to check access

	e.GET("/metrics", echoprometheus.NewHandler()) // adds route to serve gathered metrics
	rest.NewHandler(e)

	if core.AppConfig.CertPem != "" && core.AppConfig.KeyPem != "" {
		e.Logger.Fatal(e.StartTLS(":" + core.AppConfig.PortNb, []byte(core.AppConfig.CertPem), []byte(core.AppConfig.KeyPem)))
	} else {
		e.Logger.Fatal(e.Start(":" + core.AppConfig.PortNb))
	}
}
