// Don't edit this file, as it is generated by dredger
package entities

type WeatherTemperatureAlert struct {
	AlertLevel interface{} `json:"alert_level,omitempty" yaml:"alert_level,omitempty" xml:"alert_level,omitempty"`
	Message    interface{} `json:"message,omitempty" yaml:"message,omitempty" xml:"message,omitempty"`
	StationId  interface{} `json:"station_id,omitempty" yaml:"station_id,omitempty" xml:"station_id,omitempty"`
	Timestamp  interface{} `json:"timestamp,omitempty" yaml:"timestamp,omitempty" xml:"timestamp,omitempty"`
}
