// Don't edit this file, as it is generated by dredger
package entities

type WeatherHumidity struct {
	HumidityPercent interface{} `json:"humidity_percent,omitempty" yaml:"humidity_percent,omitempty" xml:"humidity_percent,omitempty"`
	StationId       interface{} `json:"station_id,omitempty" yaml:"station_id,omitempty" xml:"station_id,omitempty"`
	Timestamp       interface{} `json:"timestamp,omitempty" yaml:"timestamp,omitempty" xml:"timestamp,omitempty"`
}
