# This workflow will build the dredger packages
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up tools
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/a-h/templ/cmd/templ@latest
      
    - name: Templ
      run: templ generate web/pages/*.templ

    - name: Build
      run: go build -o dredger

    - name: Release linux binary
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: Linux Binary
        path: dredger
      
