# This workflow will publish the artifacts with goreleaser
name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
   contents: write
   packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
          cache: true
      - name: Set up tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/a-h/templ/cmd/templ@latest
      - name: Templ
        run: templ generate web/pages/*.templ
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.24.0
          args: release --clean
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Generate SBOM
        uses: CycloneDX/gh-gomod-generate-sbom@v2
        with:
          version: v1
          args: mod -licenses -json -output sbom.json
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: upload SBOM
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sbom.json
          asset_name: sbom.json
          asset_content_type: application/json